spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    fail-on-missing-locations: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

discord:
  bot-token: ${BOT_TOKEN}
  meeting-channel-id: 1082364732553560135
  listen-delay: 2000
