spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    fail-on-missing-locations: true
